site_name: pAPI – Python/Pluggable API Framework
site_description: pAPI – Official Documentación
site_author: Eduardo Miguel Fírvida Donestevez

theme:
  name: material
  language: en
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    primary: blue
    accent: light blue

markdown_extensions:
  abbr: null
  attr_list: null
  footnotes: null
  md_in_html: null
  tables: null
  toc:
    permalink: true
  pymdownx.betterem: null
  pymdownx.caret: null
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite: null
  pymdownx.keys: null
  pymdownx.mark: null
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
  pymdownx.tilde: null
  pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    - info
    - check
  pymdownx.blocks.details: null
  pymdownx.blocks.tab:
    alternate_style: true
  mdx_include: null
  markdown_include_variants: null

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [papi,papi/base]
          python:
            options:
              extensions:
              - griffe_typingdoc
              show_root_heading: true
              show_if_no_docstring: true
              preload_modules:
              - httpx
              - starlette
              - fastapi
              inherited_members: true
              members_order: source
              separate_signature: true
              unwrap_annotated: true
              filters:
              - '!^_'
              merge_init_into_class: true
              docstring_section_style: google
              signature_crossrefs: true
              show_symbol_type_heading: true
              show_symbol_type_toc: true

nav:
  - Home: index.md
  - API Reference:
      - pAPI Core:
        - Router: reference/router.md
        - Settings: reference/settings.md
        - DB: reference/db.md
        - CLI: reference/cli.md
        - Models: reference/models.md
      - build in addons:
        - Image Storage: build-in-addons/image_storage.md
        - User Authentication: build-in-addons/user_auth_system.md
