logger:
  level: "INFO"
  log_file: ./papi-tutorials.log

info:
  title: "pAPI TUTORIALS"
  version: "1.0.0"
  description: "This is a test API server for testing purposes."

server:
  host: "127.0.0.1"
  port: 8000

database:
  mongodb_uri: "mongodb://root:example@localhost:27017/extra-addons?authSource=admin"

addons:
  extra_addons_path: "extra_addons"
  enabled:
    - hello_world
    - weather
    - family_tree

